In [2]:
import pandas as pd
df=pd.read_csv("5_BanEmoHate.csv")
df

                                                Comments HateSpeech Emotion
0      যদি দেখো আকাশ ভরা তারা বুঝে নিও খেতে যাচ্ছ তুম...       hate     sad
1      ওর পুরা গুষ্টি শ্বশুরের গুষ্টি বাপের গুষ্টি সব...    nonhate   angry
2      এতদিন এসব অপকর্ম নিউজ কোথায় ছিল? দালাল সাংবাদিক।       hate   angry
3                                    নারী মানে ষড়যন্ত্র।       hate     sad
4                               চোরের মুখে বাংলার ব্যথা        hate     sad
...                                                  ...        ...     ...
16402   পারলে নিজে কিছু করে দেখান অন্যকে সমলোচনা না করে।    nonhate   happy
16403       তাই স্মার্ট বয় কত টাকা দিয়ে ফলোয়ার কিনলি     nonhate   happy
16404                                   বাজারে নতুন পাগল    nonhate   happy
16405                        ভাইটি মনে হয় অনেক স্মার্ট      nonhate   happy
16406                       ফাহিমা দিয়ে একটা নাম বানাবেন    nonhate   happy

[16407 rows x 3 columns]

In [11]:
df.drop(columns=['Emotion'], inplace=True)
df

                                                Comments HateSpeech
0      যদি দেখো আকাশ ভরা তারা বুঝে নিও খেতে যাচ্ছ তুম...       hate
1      ওর পুরা গুষ্টি শ্বশুরের গুষ্টি বাপের গুষ্টি সব...    nonhate
2      এতদিন এসব অপকর্ম নিউজ কোথায় ছিল? দালাল সাংবাদিক।       hate
3                                    নারী মানে ষড়যন্ত্র।       hate
4                               চোরের মুখে বাংলার ব্যথা        hate
...                                                  ...        ...
16402   পারলে নিজে কিছু করে দেখান অন্যকে সমলোচনা না করে।    nonhate
16403       তাই স্মার্ট বয় কত টাকা দিয়ে ফলোয়ার কিনলি     nonhate
16404                                   বাজারে নতুন পাগল    nonhate
16405                        ভাইটি মনে হয় অনেক স্মার্ট      nonhate
16406                       ফাহিমা দিয়ে একটা নাম বানাবেন    nonhate

[16407 rows x 2 columns]

In [33]:
# Robust: trim + lowercase, then map to 1/0
df['HateSpeech'] = (
    df['HateSpeech']
      .astype(str).str.strip().str.lower()
      .map({'hate': 1, 'nonhate': 0})
      .astype('Int64')  # keeps NA if anything didn't match
)
df

                                                Comments  HateSpeech
0      যদি দেখো আকাশ ভরা তারা বুঝে নিও খেতে যাচ্ছ তুম...           1
1      ওর পুরা গুষ্টি শ্বশুরের গুষ্টি বাপের গুষ্টি সব...           0
2      এতদিন এসব অপকর্ম নিউজ কোথায় ছিল? দালাল সাংবাদিক।           1
3                                    নারী মানে ষড়যন্ত্র।           1
4                               চোরের মুখে বাংলার ব্যথা            1
...                                                  ...         ...
16402   পারলে নিজে কিছু করে দেখান অন্যকে সমলোচনা না করে।           0
16403       তাই স্মার্ট বয় কত টাকা দিয়ে ফলোয়ার কিনলি            0
16404                                   বাজারে নতুন পাগল           0
16405                        ভাইটি মনে হয় অনেক স্মার্ট             0
16406                       ফাহিমা দিয়ে একটা নাম বানাবেন           0

[16407 rows x 2 columns]

In [3]:
path='Bengali hate speech .csv'
import pandas as pd
df2=pd.read_csv(path)
df2

,sentence,hate,category
0,যত্তসব পাপন শালার ফাজলামী!!!!!,1,sports
1,পাপন শালা রে রিমান্ডে নেওয়া দরকার,1,sports
2,জিল্লুর রহমান স্যারের ছেলে এতো বড় জারজ হবে এটা...,1,sports
3,শালা লুচ্চা দেখতে পাঠার মত দেখা যায়,1,sports
4,তুই তো শালা গাজা খাইছচ।তুর মার হেডায় খেলবে সাকিব,1,sports
...,...,...,...
29995,আমার মনে হচ্ছে মেনে নেয়া উচিত,0,"Meme, TikTok and others"
29996,আমি ধন্যবাদ জানাই আইনপসাসনকে,0,"Meme, TikTok and others"
29997,কাসমির কাসমিরই নিজশ্যই সাদিন হওয়ার দরকার,0,"Meme, TikTok and others"
29998,কলমি পিলিজ আপু মনি অনেক কিওট লাগছে,0,"Meme, TikTok and others"
29999,আমি পাকিস্তান এর সাথে জড়িত,0,"Meme, TikTok and others"

In [12]:
df2.drop(columns=['category'], inplace=True)
df2

                                                sentence  hate
0                         যত্তসব পাপন শালার ফাজলামী!!!!!     1
1                      পাপন শালা রে রিমান্ডে নেওয়া দরকার     1
2      জিল্লুর রহমান স্যারের ছেলে এতো বড় জারজ হবে এটা...     1
3                    শালা লুচ্চা দেখতে পাঠার মত দেখা যায়     1
4       তুই তো শালা গাজা খাইছচ।তুর মার হেডায় খেলবে সাকিব     1
...                                                  ...   ...
29995                      আমার মনে হচ্ছে মেনে নেয়া উচিত     0
29996                       আমি ধন্যবাদ জানাই আইনপসাসনকে     0
29997           কাসমির কাসমিরই নিজশ্যই সাদিন হওয়ার দরকার     0
29998                 কলমি পিলিজ আপু মনি অনেক কিওট লাগছে     0
29999                         আমি পাকিস্তান এর সাথে জড়িত     0

[30000 rows x 2 columns]

In [18]:
# exact match
df2.rename(columns={'sentence': 'Comments', 'hate': 'HateSpeech'}, inplace=True)
df2

                                                Comments  HateSpeech
0                         যত্তসব পাপন শালার ফাজলামী!!!!!           1
1                      পাপন শালা রে রিমান্ডে নেওয়া দরকার           1
2      জিল্লুর রহমান স্যারের ছেলে এতো বড় জারজ হবে এটা...           1
3                    শালা লুচ্চা দেখতে পাঠার মত দেখা যায়           1
4       তুই তো শালা গাজা খাইছচ।তুর মার হেডায় খেলবে সাকিব           1
...                                                  ...         ...
29995                      আমার মনে হচ্ছে মেনে নেয়া উচিত           0
29996                       আমি ধন্যবাদ জানাই আইনপসাসনকে           0
29997           কাসমির কাসমিরই নিজশ্যই সাদিন হওয়ার দরকার           0
29998                 কলমি পিলিজ আপু মনি অনেক কিওট লাগছে           0
29999                         আমি পাকিস্তান এর সাথে জড়িত           0

[30000 rows x 2 columns]

In [30]:
dfx = pd.read_csv('bengali_ hate_v1.0.csv', sep='\t')  # correct delimiter
# optional rename
dfx.rename(columns={'text':'Comments', 'label':'HateSpeech'}, inplace=True)

In [31]:
dfx

                                               Comments      HateSpeech
0     ইনিই হচ্ছেন ভারতের প্রতিরক্ষামন্ত্রী মনোহর পা...    Geopolitical
1       রেন্ডিয়াকে পৃথীবির মানচিএ থেকে মুচে ফেলতে হবে      Geopolitical
2     এই মালাউনরা বাংগালিদের সাফল্য দেখে হিংসা করে ব...       Religious
3                            আমরা বলতে কারা ভারত তাইতো     Geopolitical
4                                   পাকিস্তান আমার বাল     Geopolitical
...                                                 ...             ...
3413          এশালা খমতা ছেড়ে নির্বাচন দেনা খানকির পোলা        Personal
3414  সুচি ভারতের মুদির কুপরামর্শ নিয়ে বিবাধ সৃষ্টি ...    Geopolitical
3415                             হাচিনার মারে আমি চুদি   Gender abusive
3416  লাভ নাই আম্লীগ আর যে কদিন ভারতও সে কদিন এমনিতে...    Geopolitical
3417  পাকিস্তান বাংলাদেশ এক থাকলে মায়ানমার বিশাল বড় ...    Geopolitical

[3418 rows x 2 columns]

In [32]:
dfx['HateSpeech'] = 1
dfx['HateSpeech'] = dfx['HateSpeech'].astype('int64')
dfx

                                               Comments  HateSpeech
0     ইনিই হচ্ছেন ভারতের প্রতিরক্ষামন্ত্রী মনোহর পা...           1
1       রেন্ডিয়াকে পৃথীবির মানচিএ থেকে মুচে ফেলতে হবে             1
2     এই মালাউনরা বাংগালিদের সাফল্য দেখে হিংসা করে ব...           1
3                            আমরা বলতে কারা ভারত তাইতো            1
4                                   পাকিস্তান আমার বাল            1
...                                                 ...         ...
3413          এশালা খমতা ছেড়ে নির্বাচন দেনা খানকির পোলা           1
3414  সুচি ভারতের মুদির কুপরামর্শ নিয়ে বিবাধ সৃষ্টি ...           1
3415                             হাচিনার মারে আমি চুদি            1
3416  লাভ নাই আম্লীগ আর যে কদিন ভারতও সে কদিন এমনিতে...           1
3417  পাকিস্তান বাংলাদেশ এক থাকলে মায়ানমার বিশাল বড় ...           1

[3418 rows x 2 columns]

In [7]:
import pandas as pd
df4=pd.read_csv("bengali_hate_v2.0.csv")
df4

                                                   text         label  target
0     বৌদির দুধ দেকে তো আমার ই চোখ ঠিক ছিলো না - পোল...      Personal       0
1     এই সরকার কে যারা নির্লজ্জের মত সাপোর্ট দিয়েছে ...     Political       1
2     পিলখানা হত্যাকান্ড বাংলাদেশের প্রতিরক্ষা ব্যবস...  Geopolitical       3
3     ভারতের অর্থনীতি নিয়ে আপনাদের ভাবতে হবে না। ভা...  Geopolitical       3
4               খানকির পুলা মালায়নদের মেরে সাফা করে ফেল      Personal       0
...                                                 ...           ...     ...
5693  জুতা যতই দামি হোক তার স্থান পায়ে তার স্থান কখ...      Personal       0
5694  আমাদের দেশ ছোট বলে ভারতের চেয়ে পিছিয়ে, না হয়...  Geopolitical       3
5695  হিন্দুদের মধ্যে এগুলো হয় এটাই তার বাস্তব প্রমা...      Personal       0
5696         দেখলে মনে হয় শালী একটা অস্ট্রেলিয়ান গাভী       Personal       0
5697  ভাই আমি আপনার সাথে একমত। আর নারী নেতৃত্বে থাকত...     Political       1

[5698 rows x 3 columns]

In [13]:
df4.drop(columns=['label'], inplace=True)
df4

                                                   text  target
0     বৌদির দুধ দেকে তো আমার ই চোখ ঠিক ছিলো না - পোল...       0
1     এই সরকার কে যারা নির্লজ্জের মত সাপোর্ট দিয়েছে ...       1
2     পিলখানা হত্যাকান্ড বাংলাদেশের প্রতিরক্ষা ব্যবস...       3
3     ভারতের অর্থনীতি নিয়ে আপনাদের ভাবতে হবে না। ভা...       3
4               খানকির পুলা মালায়নদের মেরে সাফা করে ফেল       0
...                                                 ...     ...
5693  জুতা যতই দামি হোক তার স্থান পায়ে তার স্থান কখ...       0
5694  আমাদের দেশ ছোট বলে ভারতের চেয়ে পিছিয়ে, না হয়...       3
5695  হিন্দুদের মধ্যে এগুলো হয় এটাই তার বাস্তব প্রমা...       0
5696         দেখলে মনে হয় শালী একটা অস্ট্রেলিয়ান গাভী        0
5697  ভাই আমি আপনার সাথে একমত। আর নারী নেতৃত্বে থাকত...       1

[5698 rows x 2 columns]

In [19]:
# exact match
df4.rename(columns={'text': 'Comments', 'target': 'HateSpeech'}, inplace=True)

In [21]:
df4

                                               Comments  HateSpeech
0     বৌদির দুধ দেকে তো আমার ই চোখ ঠিক ছিলো না - পোল...           0
1     এই সরকার কে যারা নির্লজ্জের মত সাপোর্ট দিয়েছে ...           1
2     পিলখানা হত্যাকান্ড বাংলাদেশের প্রতিরক্ষা ব্যবস...           3
3     ভারতের অর্থনীতি নিয়ে আপনাদের ভাবতে হবে না। ভা...           3
4               খানকির পুলা মালায়নদের মেরে সাফা করে ফেল           0
...                                                 ...         ...
5693  জুতা যতই দামি হোক তার স্থান পায়ে তার স্থান কখ...           0
5694  আমাদের দেশ ছোট বলে ভারতের চেয়ে পিছিয়ে, না হয়...           3
5695  হিন্দুদের মধ্যে এগুলো হয় এটাই তার বাস্তব প্রমা...           0
5696         দেখলে মনে হয় শালী একটা অস্ট্রেলিয়ান গাভী            0
5697  ভাই আমি আপনার সাথে একমত। আর নারী নেতৃত্বে থাকত...           1

[5698 rows x 2 columns]

In [25]:
df4['HateSpeech'] = 1
df4['HateSpeech'] = df4['HateSpeech'].astype('int64')
df4

                                               Comments  HateSpeech
0     বৌদির দুধ দেকে তো আমার ই চোখ ঠিক ছিলো না - পোল...           1
1     এই সরকার কে যারা নির্লজ্জের মত সাপোর্ট দিয়েছে ...           1
2     পিলখানা হত্যাকান্ড বাংলাদেশের প্রতিরক্ষা ব্যবস...           1
3     ভারতের অর্থনীতি নিয়ে আপনাদের ভাবতে হবে না। ভা...           1
4               খানকির পুলা মালায়নদের মেরে সাফা করে ফেল           1
...                                                 ...         ...
5693  জুতা যতই দামি হোক তার স্থান পায়ে তার স্থান কখ...           1
5694  আমাদের দেশ ছোট বলে ভারতের চেয়ে পিছিয়ে, না হয়...           1
5695  হিন্দুদের মধ্যে এগুলো হয় এটাই তার বাস্তব প্রমা...           1
5696         দেখলে মনে হয় শালী একটা অস্ট্রেলিয়ান গাভী            1
5697  ভাই আমি আপনার সাথে একমত। আর নারী নেতৃত্বে থাকত...           1

[5698 rows x 2 columns]

In [8]:
import pandas as pd
df5=pd.read_csv("test.csv")
df5

,sentence,target,type,hate speech
0,। গরুর বাচ্চা কুকুরের বাচ্চা,ind,slander,1
1,অন্যায় দাবি করছে ক্রিকেটাররা অথচ দোষ নাকি বোর্...,ind,religion,1
2,আইসিসিকে এই তথ্য দিলো কে?শুওরের বাচ্চা পাপন,male,slander,1
3,আওয়ামীলীগ ভারতের দালাল। মোদি নির্বাচিত হওয়ার প...,group,slander,1
4,আগারওয়াল পিউর বাস্টার্ড এর কিছু হবে না???,ind,slander,1
...,...,...,...,...
5024,হেট লাইন কি দিছোফালতু হেট লাইন দেয়ার জন্যআইন অ...,NaN,NaN,0
5025,হ্যা অবশ্যই পারবে শাকিব খান যেমন সুন্দর স্মার্...,NaN,NaN,0
5026,হ্যাঁ ক্ষমা করে দিয়েছি রানু দিকে,NaN,NaN,0
5027,হ্যাঁ পমিতের যাব যেন শাকিব খানের উপজেলা এক হয়...,NaN,NaN,0
5028,হ্যালো আসসালামু আলাইকুম আল্লাহ তুমি মুসলমানদের...,NaN,NaN,0

In [15]:
df5.drop(columns=['target','type'], inplace=True)
df5

                                               sentence  hate speech
0                          । গরুর বাচ্চা কুকুরের বাচ্চা            1
1     অন্যায় দাবি করছে ক্রিকেটাররা অথচ দোষ নাকি বোর্...            1
2           আইসিসিকে এই তথ্য দিলো কে?শুওরের বাচ্চা পাপন            1
3     আওয়ামীলীগ ভারতের দালাল। মোদি নির্বাচিত হওয়ার প...            1
4             আগারওয়াল পিউর বাস্টার্ড এর কিছু হবে না???            1
...                                                 ...          ...
5024  হেট লাইন কি দিছোফালতু হেট লাইন দেয়ার জন্যআইন অ...            0
5025  হ্যা অবশ্যই পারবে শাকিব খান যেমন সুন্দর স্মার্...            0
5026                  হ্যাঁ ক্ষমা করে দিয়েছি রানু দিকে            0
5027  হ্যাঁ পমিতের যাব যেন শাকিব খানের উপজেলা এক হয়...            0
5028  হ্যালো আসসালামু আলাইকুম আল্লাহ তুমি মুসলমানদের...            0

[5029 rows x 2 columns]

In [22]:
# exact match
df5.rename(columns={'sentence': 'Comments', 'hate speech': 'HateSpeech'}, inplace=True)
df5

                                               Comments  HateSpeech
0                          । গরুর বাচ্চা কুকুরের বাচ্চা           1
1     অন্যায় দাবি করছে ক্রিকেটাররা অথচ দোষ নাকি বোর্...           1
2           আইসিসিকে এই তথ্য দিলো কে?শুওরের বাচ্চা পাপন           1
3     আওয়ামীলীগ ভারতের দালাল। মোদি নির্বাচিত হওয়ার প...           1
4             আগারওয়াল পিউর বাস্টার্ড এর কিছু হবে না???           1
...                                                 ...         ...
5024  হেট লাইন কি দিছোফালতু হেট লাইন দেয়ার জন্যআইন অ...           0
5025  হ্যা অবশ্যই পারবে শাকিব খান যেমন সুন্দর স্মার্...           0
5026                  হ্যাঁ ক্ষমা করে দিয়েছি রানু দিকে           0
5027  হ্যাঁ পমিতের যাব যেন শাকিব খানের উপজেলা এক হয়...           0
5028  হ্যালো আসসালামু আলাইকুম আল্লাহ তুমি মুসলমানদের...           0

[5029 rows x 2 columns]

In [9]:
import pandas as pd
df6=pd.read_csv("train.csv")
df6

,sentence,target,type,hate speech
0,.... ঐ ইন্দুর তোই মরছ নাই?,ind,callToViolence,1
1,#গেবনের শেষে আইসা আপনার মুখোশ টা খুলছে এতেই আম...,ind,callToViolence,1
2,✈✈✈✈��� মুরগি চোরের পাছায় ডুকবি আর মারবি।।।,ind,callToViolence,1
3,১৮ কোটির চোদা খাওয়া শেষে এখন ১৫০কোটির চোদা খাব...,female,callToViolence,1
4,২য় মীর জাফরের মুখে মুতে দে...,male,callToViolence,1
...,...,...,...,...
40219,��� গানটা চালু করে ওয়াস রুমে গিয়েছিলাম! এসে দে...,NaN,NaN,0
40220,���� হালকার উপজেলা ঝাপসা,NaN,NaN,0
40221,���� ��,NaN,NaN,0
40222,���� ��পুরাই আগুনের গুলা� () ��,NaN,NaN,0
40223,������� মজা পাইলাম �����,NaN,NaN,0

In [16]:
df6.drop(columns=['target','type'], inplace=True)
df6

                                                sentence  hate speech
0                             .... ঐ ইন্দুর তোই মরছ নাই?            1
1      #গেবনের শেষে আইসা আপনার মুখোশ টা খুলছে এতেই আম...            1
2            ✈✈✈✈��� মুরগি চোরের পাছায় ডুকবি আর মারবি।।।            1
3      ১৮ কোটির চোদা খাওয়া শেষে এখন ১৫০কোটির চোদা খাব...            1
4                          ২য় মীর জাফরের মুখে মুতে দে...            1
...                                                  ...          ...
40219  ��� গানটা চালু করে ওয়াস রুমে গিয়েছিলাম! এসে দে...            0
40220                           ���� হালকার উপজেলা ঝাপসা            0
40221                                            ���� ��            0
40222                    ���� ��পুরাই আগুনের গুলা� () ��            0
40223                           ������� মজা পাইলাম �����            0

[40224 rows x 2 columns]

In [23]:
# exact match
df6.rename(columns={'sentence': 'Comments', 'hate speech': 'HateSpeech'}, inplace=True)
df6

                                                Comments  HateSpeech
0                             .... ঐ ইন্দুর তোই মরছ নাই?           1
1      #গেবনের শেষে আইসা আপনার মুখোশ টা খুলছে এতেই আম...           1
2            ✈✈✈✈��� মুরগি চোরের পাছায় ডুকবি আর মারবি।।।           1
3      ১৮ কোটির চোদা খাওয়া শেষে এখন ১৫০কোটির চোদা খাব...           1
4                          ২য় মীর জাফরের মুখে মুতে দে...           1
...                                                  ...         ...
40219  ��� গানটা চালু করে ওয়াস রুমে গিয়েছিলাম! এসে দে...           0
40220                           ���� হালকার উপজেলা ঝাপসা           0
40221                                            ���� ��           0
40222                    ���� ��পুরাই আগুনের গুলা� () ��           0
40223                           ������� মজা পাইলাম �����           0

[40224 rows x 2 columns]

In [10]:
import pandas as pd
df7=pd.read_csv("val.csv")
df7

,sentence,target,type,hate speech
0,- চ্যার দয়া করে বমি করার সময় পলিথিনে করবেন আর ...,male,slander,1
1,", জাফর সার অবশ্যই জ্ঞানী মানুষ, বাট এক কুখ্যাত...",male,religion_slander,1
2,? এই মাইয়া আমার লাগবো লাগবো ? নাইলে রাতে ঘুম ...,female,callToViolence_gender,1
3,।। জবর ইকবাল তুমি আমার বালের টিচার।। তোর রিয়েল...,male,slander,1
4,#দালাল #দলকানা #যাফ্রিকবাল,male,slander,1
...,...,...,...,...
5023,হে বাংলার সাহসী সেনাবাহিনীরা তোমরা কি এখনো ঘুম...,NaN,NaN,0
5024,হেআল্লাহ সব তোমাৰ হাতেতুমি ৰক্ষা কৰবেএবংহাজাৰ ...,NaN,NaN,0
5025,হ্যা এই মেয়ে লাইভে আসো,NaN,NaN,0
5026,হ্যািপ ঠিক কাজ করেছে।এই মত আমি জীবনে ভালোবাসা ...,NaN,NaN,0
5027,�দেওয়ানবাগির গুলা দিসে �,NaN,NaN,0

In [17]:
df7.drop(columns=['target','type'], inplace=True)
df7

                                               sentence  hate speech
0     - চ্যার দয়া করে বমি করার সময় পলিথিনে করবেন আর ...            1
1     , জাফর সার অবশ্যই জ্ঞানী মানুষ, বাট এক কুখ্যাত...            1
2     ? এই মাইয়া আমার লাগবো লাগবো ? নাইলে রাতে ঘুম ...            1
3     ।। জবর ইকবাল তুমি আমার বালের টিচার।। তোর রিয়েল...            1
4                            #দালাল #দলকানা #যাফ্রিকবাল            1
...                                                 ...          ...
5023  হে বাংলার সাহসী সেনাবাহিনীরা তোমরা কি এখনো ঘুম...            0
5024  হেআল্লাহ সব তোমাৰ হাতেতুমি ৰক্ষা কৰবেএবংহাজাৰ ...            0
5025                             হ্যা এই মেয়ে লাইভে আসো            0
5026  হ্যািপ ঠিক কাজ করেছে।এই মত আমি জীবনে ভালোবাসা ...            0
5027                           �দেওয়ানবাগির গুলা দিসে �            0

[5028 rows x 2 columns]

In [24]:
# exact match
df7.rename(columns={'sentence': 'Comments', 'hate speech': 'HateSpeech'}, inplace=True)
df7

                                               Comments  HateSpeech
0     - চ্যার দয়া করে বমি করার সময় পলিথিনে করবেন আর ...           1
1     , জাফর সার অবশ্যই জ্ঞানী মানুষ, বাট এক কুখ্যাত...           1
2     ? এই মাইয়া আমার লাগবো লাগবো ? নাইলে রাতে ঘুম ...           1
3     ।। জবর ইকবাল তুমি আমার বালের টিচার।। তোর রিয়েল...           1
4                            #দালাল #দলকানা #যাফ্রিকবাল           1
...                                                 ...         ...
5023  হে বাংলার সাহসী সেনাবাহিনীরা তোমরা কি এখনো ঘুম...           0
5024  হেআল্লাহ সব তোমাৰ হাতেতুমি ৰক্ষা কৰবেএবংহাজাৰ ...           0
5025                             হ্যা এই মেয়ে লাইভে আসো           0
5026  হ্যািপ ঠিক কাজ করেছে।এই মত আমি জীবনে ভালোবাসা ...           0
5027                           �দেওয়ানবাগির গুলা দিসে �           0

[5028 rows x 2 columns]

In [34]:
import pandas as pd

# 1) Row-wise merge
df_all = pd.concat([df, df2, dfx, df4, df5, df6, df7], ignore_index=True)

# 2) Make sure the key columns exist and align
expected_cols = ['Comments', 'HateSpeech']
for col in expected_cols:
    if col not in df_all.columns:
        df_all[col] = pd.NA

# 3) Coerce HateSpeech to 0/1 ints (keep NA if unexpected values)
df_all['HateSpeech'] = (
    pd.to_numeric(df_all['HateSpeech'], errors='coerce')
      .astype('Int64')
      .fillna(0)
      .astype(int)
)

# 4) Sort so 1s are first, 0s at the bottom (stable keeps original order within each group)
df_all = df_all.sort_values('HateSpeech', ascending=False, kind='stable').reset_index(drop=True)

# (optional) Reorder columns, drop exact duplicates, and quick check
df_all = df_all[[c for c in expected_cols if c in df_all.columns] + [c for c in df_all.columns if c not in expected_cols]]
df_all = df_all.drop_duplicates(subset=['Comments', 'HateSpeech'])
print(df_all['HateSpeech'].value_counts())

HateSpeech
0    44413
1    40945
Name: count, dtype: int64

In [35]:
df_all.to_csv('merged_hatespeech.csv', index=False, encoding='utf-8')